// <auto-generated />
using System;
using Magic8Ball.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Magic8Ball.Infra.Data.Migrations
{
    [DbContext(typeof(DefaultDbContext))]
    partial class DefaultDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("Magic8Ball.Domain.Entities.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("varchar(800)");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("Answer", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 5, 22, 2, 45, 14, 252, DateTimeKind.Utc).AddTicks(6649),
                            IsActive = true,
                            Message = "It is certain.",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 5, 22, 2, 45, 14, 252, DateTimeKind.Utc).AddTicks(6656),
                            IsActive = true,
                            Message = "It is decidedly so.",
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 5, 22, 2, 45, 14, 252, DateTimeKind.Utc).AddTicks(6657),
                            IsActive = true,
                            Message = "Without a doubt.",
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 5, 22, 2, 45, 14, 252, DateTimeKind.Utc).AddTicks(6658),
                            IsActive = true,
                            Message = "Yes definitely.",
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 5, 22, 2, 45, 14, 252, DateTimeKind.Utc).AddTicks(6658),
                            IsActive = true,
                            Message = "You may rely on it.",
                            Type = 0
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 5, 22, 2, 45, 14, 252, DateTimeKind.Utc).AddTicks(6659),
                            IsActive = true,
                            Message = "As I see it, yes.",
                            Type = 0
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 5, 22, 2, 45, 14, 252, DateTimeKind.Utc).AddTicks(6660),
                            IsActive = true,
                            Message = "Most likely.",
                            Type = 0
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 5, 22, 2, 45, 14, 252, DateTimeKind.Utc).AddTicks(6661),
                            IsActive = true,
                            Message = "Outlook good.",
                            Type = 0
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2024, 5, 22, 2, 45, 14, 252, DateTimeKind.Utc).AddTicks(6662),
                            IsActive = true,
                            Message = "Yes.",
                            Type = 0
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2024, 5, 22, 2, 45, 14, 252, DateTimeKind.Utc).AddTicks(6662),
                            IsActive = true,
                            Message = "Signs point to yes.",
                            Type = 0
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2024, 5, 22, 2, 45, 14, 252, DateTimeKind.Utc).AddTicks(6663),
                            IsActive = true,
                            Message = "Reply hazy, try again.",
                            Type = 1
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2024, 5, 22, 2, 45, 14, 252, DateTimeKind.Utc).AddTicks(6664),
                            IsActive = true,
                            Message = "Ask again later.",
                            Type = 1
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2024, 5, 22, 2, 45, 14, 252, DateTimeKind.Utc).AddTicks(6665),
                            IsActive = true,
                            Message = "Better not tell you now.",
                            Type = 1
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2024, 5, 22, 2, 45, 14, 252, DateTimeKind.Utc).AddTicks(6666),
                            IsActive = true,
                            Message = "Cannot predict now.",
                            Type = 1
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2024, 5, 22, 2, 45, 14, 252, DateTimeKind.Utc).AddTicks(6666),
                            IsActive = true,
                            Message = "Concentrate and ask again.",
                            Type = 1
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2024, 5, 22, 2, 45, 14, 252, DateTimeKind.Utc).AddTicks(6667),
                            IsActive = true,
                            Message = "Don't count on it.",
                            Type = 2
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2024, 5, 22, 2, 45, 14, 252, DateTimeKind.Utc).AddTicks(6668),
                            IsActive = true,
                            Message = "My reply is no.",
                            Type = 2
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2024, 5, 22, 2, 45, 14, 252, DateTimeKind.Utc).AddTicks(6669),
                            IsActive = true,
                            Message = "My sources say no.",
                            Type = 2
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2024, 5, 22, 2, 45, 14, 252, DateTimeKind.Utc).AddTicks(6670),
                            IsActive = true,
                            Message = "Outlook not so good.",
                            Type = 2
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2024, 5, 22, 2, 45, 14, 252, DateTimeKind.Utc).AddTicks(6670),
                            IsActive = true,
                            Message = "Very doubtful.",
                            Type = 2
                        });
                });

            modelBuilder.Entity("Magic8Ball.Domain.Entities.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<double>("ElapsedTime")
                        .HasColumnType("REAL");

                    b.Property<string>("EndPoint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HttpVerb")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LogMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadRequest")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadResponse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("Log", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
